(()=>{
  'use strict';
  const App=window.SAGRecruitment,Core=window.SAGStoryCore;if(!App||!Core)throw new Error('SAG finale dependencies missing');
  const content=document.getElementById('sagStoryContent'),tabs=document.getElementById('sagStoryTabs');
  function ensureAdmissionTab(){if(tabs.querySelector('[data-sag-tab="admission"]'))return;const button=document.createElement('button');button.type='button';button.dataset.sagTab='admission';button.textContent='AUFNAHME';tabs.append(button)}
  function criterion(label,done,detail){return `<article class="sag-criterion ${done?'done':''}"><b>${label}</b><span>${done?'ERFÜLLT':detail}</span></article>`}
  function renderAdmission(){
    const story=App.story,states=Core.campaignStates(story,App.getBase(),App.getProgression()),allMissions=states.every(item=>item.claimed),faction=story.faction?Core.FACTIONS[story.faction]:null;
    content.innerHTML=`<header class="sag-section-head"><div><span class="sag-kicker">SPRINT 19 // SAG AUFNAHME</span><h2>${story.admitted?'MITGLIEDSSTATUS BESTÄTIGT':'LETZTE AUFNAHMEPRÜFUNG'}</h2></div><p>${story.admitted?'Dein Rekrutierungsprofil wurde in die SAG-Chronik übernommen.':'Kiwimi bewertet Ruf, Vertrauen, Kampagne und deine Fähigkeit, Wissen in Verantwortung zu übersetzen.'}</p></header><div class="sag-admission-grid"><section class="sag-admission-main"><span class="sag-kicker">STAR ATLAS GERMANY // ${Core.candidateStatus(story)}</span><div class="sag-admission-seal">SAG</div><h2>${story.admitted?endingTitle(story):'DEIN PLATZ IST NOCH NICHT VERDIENT.'}</h2><p>${story.admitted?endingText(story,faction):'Schließe die Kampagne ab und erfülle die Aufnahmebedingungen. Stärke allein reicht nicht: SAG erwartet, dass andere Piloten von deiner Anwesenheit profitieren.'}</p>${story.admitted?`<article class="sag-member-card"><span>OFFIZIELLE AUFNAHME</span><h3>${faction?.name||'FRAKTIONSLOS'} // ${story.ending?.toUpperCase()||'MEMBER'}</h3><p>Kiwimi hat deine Aufnahme als Teil von Star Atlas Germany bestätigt.</p></article>`:''}<div class="sag-profile-actions"><button id="sagAdmissionCampaign" class="sag-btn ${story.admitted?'':'primary'}">KAMPAGNE ANZEIGEN</button>${story.admitted?'<button id="sagReplayFinale" class="sag-btn primary">ZEREMONIE ERNEUT</button>':''}</div></section><aside class="sag-admission-side"><span class="sag-kicker">AUFNAHMEKRITERIEN</span><h3>Die SAG-Charta in messbarer Form</h3><p>Die Zahlen öffnen den Kanal. Kiwimis Bewertung entsteht aus dem Weg dorthin.</p><div class="sag-criteria-list">${criterion('Fraktion gewählt',Boolean(story.faction),'MUD, ONI oder Ustur')}${criterion('SAG-Ruf 70+',story.sagReputation>=70,`${story.sagReputation} / 70`)}${criterion('Kiwimi-Vertrauen 55+',story.kiwimiTrust>=55,`${story.kiwimiTrust} / 55`)}${criterion('15 Kampagnenmissionen',allMissions,`${story.claimedMissions.length} / ${Core.MISSIONS.length}`)}${criterion('SAG-Codex aufgebaut',story.loreUnlocked.length>=6,`${story.loreUnlocked.length} / 6`)}</div></aside></div><section class="sag-polish-grid"><article><b>FRAKTIONSIDENTITÄT</b><span>Deine Herkunft bleibt sichtbar, ohne die SAG-Zugehörigkeit zu ersetzen.</span></article><article><b>COMMUNITY-AUFTRAG</b><span>Entdecken, verbinden und bewähren sind die drei Leitwerte der Kampagne.</span></article><article><b>NÄCHSTE VERANTWORTUNG</b><span>Aufgenommene Mitglieder werden vom Anwärter zum Vorbild für neue Piloten.</span></article></section>`;
    document.getElementById('sagAdmissionCampaign')?.addEventListener('click',()=>App.setTab('campaign'));document.getElementById('sagReplayFinale')?.addEventListener('click',()=>showFinale(story,true));
  }
  function endingTitle(story){if(story.ending==='elite')return'SAG ELITE-PILOT';if(story.ending?.includes('envoy'))return'FRAKTIONSGESANDTER VON SAG';return'WILLKOMMEN BEI SAG'}
  function endingText(story,faction){if(story.ending==='elite')return'Kiwimi erkennt dich nicht nur als Mitglied an, sondern als Piloten, dem andere Anwärter folgen können. Dein Ruf, dein Vertrauen und deine Kampagnenleistung bilden das stärkste Aufnahmeprofil.';if(story.ending?.includes('envoy'))return`Du bleibst sichtbar mit ${faction?.name||'deiner Fraktion'} verbunden und hast zugleich bewiesen, dass du ihre Stärken in den Dienst von SAG stellen kannst.`;return'Du hast gezeigt, dass Verlässlichkeit, Wissen und gemeinsames Handeln mehr Gewicht haben als ein einzelner perfekter Einsatz.'}
  function stars(){return Array.from({length:24},(_,index)=>`<i style="--angle:${index*15}deg;--delay:${-(index%7)*.23}s;--spark:${index%3===0?'#d7a83c':'#61e7ff'}"></i>`).join('')}
  function showFinale(story=App.story,replay=false){
    const overlay=document.getElementById('sagStoryScene');if(!overlay)return;const faction=story.faction?Core.FACTIONS[story.faction]:null;overlay.classList.remove('sag-hidden');overlay.classList.add('sag-finale');overlay.innerHTML=`<div class="sag-finale-stars">${stars()}</div><article class="sag-finale-panel"><div class="sag-finale-emblem">SAG</div><span>STAR ATLAS GERMANY // AUFNAHME BESTÄTIGT</span><h2>${endingTitle(story)}</h2><p>${endingText(story,faction)}</p><blockquote class="sag-finale-quote">„Du bist nicht aufgenommen, weil du jede Antwort kanntest. Du bist aufgenommen, weil du gelernt hast, die richtigen Fragen gemeinsam zu stellen.“<br><small>— KIWIMI, GRÜNDER VON SAG</small></blockquote><div class="sag-finale-actions"><button id="sagAcceptMembership" class="sag-btn primary">${replay?'ZURÜCK ZUM HQ':'MITGLIEDSCHAFT ANNEHMEN'}</button><button id="sagReturnHangarFinal" class="sag-btn">ZUM HANGAR</button></div></article>`;
    const close=tab=>{overlay.classList.add('sag-hidden');overlay.classList.remove('sag-finale');overlay.innerHTML='';if(tab){App.openHQ(tab)}};document.getElementById('sagAcceptMembership').addEventListener('click',()=>close('admission'));document.getElementById('sagReturnHangarFinal').addEventListener('click',()=>{close();App.closeHQ()});
    if(!replay){const next={...story,seenScenes:[...new Set([...(story.seenScenes||[]),'sag-admission-finale'])]};App.saveStory(next)}
  }
  function addMemberIndicator(){let node=document.getElementById('sagMemberIndicator');if(App.story.admitted&&!node){node=document.createElement('div');node.id='sagMemberIndicator';node.className='sag-member-indicator';node.textContent='◆ SAG MITGLIED';document.body.append(node)}if(!App.story.admitted&&node)node.remove()}
  function onAdmission(story){addMemberIndicator();setTimeout(()=>showFinale(story),350)}
  ensureAdmissionTab();App.registerTab('admission',renderAdmission);App.onAdmission=onAdmission;App.showFinale=showFinale;addMemberIndicator();
  if(App.story.admitted&&!App.story.seenScenes.includes('sag-admission-finale'))setTimeout(()=>showFinale(App.story),900);
  const observer=new MutationObserver(()=>addMemberIndicator());observer.observe(document.getElementById('sagStoryShell'),{attributes:true,attributeFilter:['class']});
})();