const fs=require('node:fs');
const assert=require('node:assert/strict');
const html=fs.readFileSync('sprint25.html','utf8');
for(const file of ['sprint21-canon-lore.js','sprint22-sag-dac.js','sprint23-campaign-narrative.js','sprint24-kiwimi-dialogue.js','sprint24-kiwimi-dialogue.css','sprint25-narrative-ui.js','sprint25-narrative.css','sprint25-finale-editorial.js'])assert.ok(fs.existsSync(file)&&fs.statSync(file).size>0,file);
assert.match(html,/data-build="0250"/);
assert.match(html,/Galia Narrative 0\.25/);
assert.match(html,/sprint21-canon-lore\.js\?build=0250/);
assert.match(html,/sprint24-kiwimi-dialogue\.css\?build=0250/);
assert.match(html,/sprint25-finale-editorial\.js\?build=0250/);
assert.doesNotMatch(html,/sag-frontier-reset-v025/);
const positions=['sprint15-story-core.js','sprint21-canon-lore.js','sprint22-sag-dac.js','sprint23-campaign-narrative.js','sprint15-cinematic.js','sprint24-kiwimi-dialogue.js','sprint25-narrative-ui.js','sprint25-finale-editorial.js'].map(name=>html.indexOf(name));
assert.ok(positions.every((value,index)=>value>=0&&(index===0||value>positions[index-1])));
const dialogue=fs.readFileSync('sprint24-kiwimi-dialogue.js','utf8');
assert.match(dialogue,/Muss SAG wirklich multifraktional sein/);
assert.match(dialogue,/keine offizielle Institution/);
assert.match(dialogue,/dialogue:\$\{id\}/);
const ui=fs.readFileSync('sprint25-narrative-ui.js','utf8');
assert.match(ui,/STAR ATLAS KANON/);
assert.match(ui,/Kanon, SAG-Chronik und Feldberichte/);
assert.match(ui,/SAG IST KEINE VIERTE FRAKTION/);
console.log('sprint25 static integration tests passed');