const fs=require('node:fs');
const assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/../sprint20.html','utf8');
const css=fs.readFileSync(__dirname+'/../sprint20-focused.css','utf8');
const ui=fs.readFileSync(__dirname+'/../sprint20-focused.js','utf8');
assert.match(html,/Focused Interface 0\.20/);
assert.match(html,/sprint20-focused\.css\?build=0200/);
assert.match(html,/sprint20-focused\.js\?build=0200/);
assert.doesNotMatch(html,/sag-frontier-reset-v020/);
assert.match(css,/\.focus-mission/);
assert.match(css,/\.focus-lore/);
assert.match(css,/\.focus-profile/);
assert.match(css,/#commandToggle\{display:none!important\}/);
assert.match(ui,/Nur das nächste relevante Ziel/);
assert.match(ui,/Gesperrte Inhalte werden nicht als große leere Karten gezeigt/);
assert.match(ui,/App\.refreshCampaign=/);
assert.match(ui,/data-sag-tab="campaign"/);
assert.ok(css.length>9000);
assert.ok(ui.length>12000);
console.log('sprint20 focused static tests passed');
