const fs=require('node:fs');
const assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/../sprint14.html','utf8');
const core=fs.readFileSync(__dirname+'/../sprint14-progression-core.js','utf8');
const advanced=fs.readFileSync(__dirname+'/../sprint14-progression-advanced.js','utf8');
const ui=fs.readFileSync(__dirname+'/../sprint14-progression-ui.js','utf8');
const advancedUi=fs.readFileSync(__dirname+'/../sprint14-progression-advanced-ui.js','utf8');
const bootstrap=fs.readFileSync(__dirname+'/../sprint14-bootstrap.js','utf8');
const css=fs.readFileSync(__dirname+'/../sprint14-progression.css','utf8');
const advancedCss=fs.readFileSync(__dirname+'/../sprint14-progression-advanced.css','utf8');
assert.match(html,/sprint13\.html\?build=0142/);
assert.match(html,/Command Progression 0\.14\.2/i);
assert.match(html,/sag-frontier-reset-v0142/);
assert.match(html,/sprint14-bootstrap\.js\?build=0142/);
assert.match(html,/sprint14-progression-advanced\.js/);
assert.match(html,/sprint14-progression-advanced-ui\.js/);
assert.match(html,/sprint14-progression-advanced\.css/);
assert.match(html,/commandCenter/);
assert.ok(core.length>10000);
assert.ok(advanced.length>10000);
assert.ok(ui.length>8000);
assert.ok(advancedUi.length>8000);
assert.ok(bootstrap.length>600);
assert.ok(css.length>3000);
assert.ok(advancedCss.length>1500);
assert.match(advanced,/campaignStates/);
assert.match(advanced,/purchaseResearch/);
assert.match(advancedUi,/renderCampaign/);
assert.match(advancedUi,/patchContractCost/);
assert.match(bootstrap,/revealCommand/);
assert.match(bootstrap,/commandVisible:true/);
assert.match(bootstrap,/serviceWorker/);
console.log('sprint14 static integration tests passed');
