'use strict';
(()=>{
 const frame=document.getElementById('baseBuild');if(!frame)return;
 const state={menu:false,resume:false,doc:null};
 const overlay=document.createElement('div');overlay.className='s42-overlay';
 const toggle=document.createElement('button');toggle.type='button';toggle.className='s42-menu-button';toggle.setAttribute('aria-expanded','false');toggle.innerHTML='<span class="burger" aria-hidden="true"><i></i><i></i><i></i></span><span>Menü</span>';
 const drawer=document.createElement('aside');drawer.className='s42-drawer';drawer.setAttribute('aria-hidden','true');drawer.innerHTML='<div class="s42-head"><div><small>S.A.G. Frontier</small><h2>Zentrales Menü</h2></div><button type="button" class="s42-close" aria-label="Menü schließen">×</button></div><div class="s42-section"><p class="s42-copy">Alle Systeme öffnen sich von hier aus. Während des Spielens bleibt nur das notwendige HUD sichtbar.</p><div class="s42-actions"><button class="s42-action" data-open="resume"><span><strong>Zurück ins Spiel</strong><span>Alle Fenster schließen und Run fortsetzen.</span></span><b>›</b></button><button class="s42-action" data-open="cycle"><span><strong>Frontier-Zyklus</strong><span>Monatsfortschritt, Phasen und Boss-Codex.</span></span><b>›</b></button><button class="s42-action" data-open="command"><span><strong>Command</strong><span>Karriere, Verträge, Forschung und Archiv.</span></span><b>›</b></button><button class="s42-action" data-open="sag"><span><strong>SAG HQ</strong><span>Kampagne, Wissen, Profil und Fraktion.</span></span><b>›</b></button><button class="s42-action" data-open="galia"><span><strong>Galia Ops</strong><span>Karte, Markt, Schiff, Ruf und Archiv.</span></span><b>›</b></button></div><div class="s42-meta"><div class="s42-card"><small>Ingame</small><b>Nur HUD + Menü</b></div><div class="s42-card"><small>Fenster</small><b>Immer mit X schließbar</b></div></div></div>';
 document.body.append(toggle,overlay,drawer);
 const app=()=>{const mid=frame.contentDocument,stable=mid?.getElementById('stableBuild');return stable?.contentDocument||null};
 const game=()=>app()?.getElementById('gameFrame')?.contentWindow?.SAG||null;
 function pause(){const g=game();if(g?.state==='running'&&g.pauseGame){state.resume=true;try{g.pauseGame()}catch{}}}
 function resume(){const g=game();if(state.resume&&g?.state==='paused'&&g.resumeGame){state.resume=false;try{g.resumeGame()}catch{}}}
 function openMenu(){pause();state.menu=true;overlay.classList.add('open');drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');toggle.setAttribute('aria-expanded','true')}
 function closeMenu(){state.menu=false;window.SAGFrontierCycle?.close();overlay.classList.remove('open');drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');toggle.setAttribute('aria-expanded','false')}
 function closePanel(id){const d=app(),p=d?.getElementById(id);if(!p)return;if(id==='commandCenter'){p.classList.add('hidden');d.getElementById('commandToggle')?.setAttribute('aria-expanded','false')}else if(id==='galiaShell')p.classList.add('g-hidden');else p.classList.add('sag-hidden')}
 function closeAll(){window.SAGFrontierCycle?.close();closePanel('commandCenter');closePanel('sagStoryShell');closePanel('galiaShell');const d=app();['sagIntro','sagFactionStage','sagEventOverlay','sagStoryScene'].forEach(id=>d?.getElementById(id)?.classList.add('sag-hidden'))}
 function attachCycle(){const p=window.SAGFrontierCycle?.panel,section=drawer.querySelector('.s42-section'),meta=drawer.querySelector('.s42-meta');if(p&&section&&p.parentElement!==section)meta?.before(p)}
 function openPanel(type){if(type==='cycle'){closeAll();attachCycle();window.SAGFrontierCycle?.open();return}const d=app();if(!d)return;closeAll();const id={command:'commandToggle',sag:'sagStoryToggle',galia:'galiaToggle'}[type];d.getElementById(id)?.click()}
 function bindRuntime(){const d=app();if(!d||state.doc===d)return;state.doc=d;d.body.dataset.s42MenuManaged='true';let style=d.getElementById('s42-menu-runtime-style');if(!style){style=d.createElement('style');style.id='s42-menu-runtime-style';style.textContent='body[data-s42-menu-managed="true"] #commandToggle,body[data-s42-menu-managed="true"] #sagStoryToggle,body[data-s42-menu-managed="true"] #galiaToggle{display:none!important}body[data-s42-menu-managed="true"] .command-center,body[data-s42-menu-managed="true"] .sag-story-shell,body[data-s42-menu-managed="true"] #galiaShell{z-index:1200!important}body[data-s42-menu-managed="true"] .command-header button,body[data-s42-menu-managed="true"] .sag-hq-header button,body[data-s42-menu-managed="true"] .g-head button{display:grid!important;place-items:center!important}';d.head.append(style)}
  [['commandCenter','commandClose','.command-header'],['sagStoryShell','sagStoryClose','.sag-hq-header'],['galiaShell','galiaClose','.g-head']].forEach(([panel,id,header])=>{const p=d.getElementById(panel);if(!p)return;let b=d.getElementById(id);if(!b){b=d.createElement('button');b.id=id;b.type='button';b.textContent='×';b.setAttribute('aria-label','Fenster schließen');p.querySelector(header)?.append(b)}if(b&&!b.dataset.s42){b.dataset.s42='1';b.addEventListener('click',()=>{closePanel(panel);resume()})}});closeAll()}
 toggle.addEventListener('click',()=>state.menu?closeMenu():openMenu());overlay.addEventListener('click',closeMenu);drawer.querySelector('.s42-close').addEventListener('click',closeMenu);drawer.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(!b)return;const type=b.dataset.open;if(type==='resume'){closeAll();closeMenu();resume()}else{openPanel(type);closeMenu()}});
 frame.addEventListener('load',()=>{state.doc=null;setTimeout(bindRuntime,0)});attachCycle();setInterval(()=>{bindRuntime();attachCycle()},400);
})();
