(()=>{'use strict';
const STORAGE='sag-month-frontier-v042';
const defaults=()=>({runs:0,commandXp:0,research:0,contracts:0,campaign:0,galia:0,combat:0,exploration:0,salvage:0,bosses:[],bestWave:1,phase:1});
const load=()=>{try{return Object.assign(defaults(),JSON.parse(localStorage.getItem(STORAGE)||'{}'))}catch{return defaults()}};
const save=m=>localStorage.setItem(STORAGE,JSON.stringify(m));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const bossRoster=[
{id:'warden',name:'FRONTIER WARDEN',color:'#ff5577',core:'#ffd36a',hp:1,move:'hunt',pattern:'fan'},
{id:'corsair',name:'VOID CORSAIR',color:'#ff9c4b',core:'#fff0a0',hp:1.08,move:'strafe',pattern:'burst'},
{id:'bastion',name:'AEGIS BASTION',color:'#8d76ff',core:'#e5dcff',hp:1.28,move:'anchor',pattern:'rings'},
{id:'stalker',name:'RIFT STALKER',color:'#42e7ca',core:'#e9fff9',hp:.96,move:'blink',pattern:'cross'},
{id:'carrier',name:'SWARM CARRIER',color:'#9ddd5c',core:'#f2ffd7',hp:1.18,move:'orbit',pattern:'summon'},
{id:'prism',name:'PRISM REGENT',color:'#74dfff',core:'#ffffff',hp:1.2,move:'orbit',pattern:'prism'},
{id:'gravity',name:'GRAVITY HARVESTER',color:'#c576ff',core:'#f1cfff',hp:1.36,move:'anchor',pattern:'gravity'},
{id:'tempest',name:'ION TEMPEST',color:'#55a7ff',core:'#d9ecff',hp:1.02,move:'dash',pattern:'tempest'},
{id:'foundry',name:'WAR FOUNDRY',color:'#ff704f',core:'#ffe0ba',hp:1.42,move:'strafe',pattern:'foundry'},
{id:'oracle',name:'ABYSSAL ORACLE',color:'#5ef0d2',core:'#d7fff8',hp:1.3,move:'blink',pattern:'oracle'}
];
const extraProfiles=[
{name:'skirmisher',color:'#55d8ff',core:'#eefcff',speed:128,hp:3,damage:11,score:34,xp:18,radius:17,weight:12,mode:'skirmisher',unlock:2},
{name:'leech',color:'#eb5e9f',core:'#ffd6e9',speed:112,hp:5,damage:12,score:42,xp:23,radius:20,weight:9,mode:'leech',unlock:3},
{name:'minelayer',color:'#ffb34f',core:'#fff0bd',speed:76,hp:5,damage:15,score:48,xp:25,radius:22,weight:8,mode:'minelayer',unlock:4},
{name:'splitter',color:'#83ed78',core:'#efffeb',speed:105,hp:6,damage:14,score:52,xp:27,radius:24,weight:8,mode:'splitter',unlock:5},
{name:'disruptor',color:'#9a82ff',core:'#eee9ff',speed:92,hp:6,damage:16,score:58,xp:30,radius:22,weight:7,mode:'disruptor',unlock:6},
{name:'artillery',color:'#ff6a66',core:'#ffe1df',speed:48,hp:9,damage:24,score:74,xp:38,radius:29,weight:5,mode:'artillery',unlock:7},
{name:'commander',color:'#f5dc58',core:'#fffbd8',speed:67,hp:11,damage:18,score:92,xp:46,radius:31,weight:3,mode:'commander',unlock:8}
];
function phaseFor(m){const score=m.runs/18+m.commandXp/850+m.research/8+m.contracts/12+m.campaign/6+m.galia/8+(m.combat+m.exploration+m.salvage)/24+m.bosses.length/7;return score>=7?4:score>=4?3:score>=1.8?2:1}
function completion(m){const parts=[m.runs/72,m.commandXp/1800,m.research/12,m.contracts/18,m.campaign/8,m.galia/10,m.combat/10,m.exploration/10,m.salvage/10,m.bosses.length/7];return Math.round(clamp(parts.reduce((a,b)=>a+Math.min(1,b),0)/parts.length,0,1)*100)}
function makePanel(){const p=document.createElement('section');p.id='frontierCyclePanel';p.className='s42-panel s42-hidden';p.setAttribute('aria-hidden','true');p.innerHTML='<div class="s42-panel-head"><div><small>Fortschritt</small><h2>FRONTIER-ZYKLUS</h2></div><button class="s42-cycle-close" type="button" aria-label="Frontier-Zyklus schließen">×</button></div><p data-s42-sub></p><div class="s42-grid"></div>';document.body.append(p);return p}
const panel=makePanel();
const cycleApi={panel,open(){panel.classList.remove('s42-hidden');panel.setAttribute('aria-hidden','false')},close(){panel.classList.add('s42-hidden');panel.setAttribute('aria-hidden','true')}};
panel.querySelector('.s42-cycle-close').addEventListener('click',()=>cycleApi.close());
window.SAGFrontierCycle=cycleApi;
function renderMeta(m){m.phase=phaseFor(m);save(m);const names=['AUFBRUCH','SPEZIALISIERUNG','VERNETZUNG','MEISTERSCHAFT'];const pct=completion(m);panel.querySelector('[data-s42-sub]').textContent=`Phase ${m.phase}: ${names[m.phase-1]} · Monatsfortschritt ${pct}%`;const rows=[['Runs',`${m.runs} / 72`,m.runs/72],['Command',`${m.commandXp} / 1800`,m.commandXp/1800],['Forschung',`${m.research} / 12`,m.research/12],['Verträge',`${m.contracts} / 18`,m.contracts/18],['Kampagne',`${m.campaign} / 8`,m.campaign/8],['Galia',`${m.galia} / 10`,m.galia/10],['Meisterschaften',`${m.combat+m.exploration+m.salvage} / 30`,(m.combat+m.exploration+m.salvage)/30],['Boss-Codex',`${m.bosses.length} / 7`,m.bosses.length/7]];panel.querySelector('.s42-grid').innerHTML=rows.map(r=>`<div class="s42-card"><span>${r[0]}</span><b>${r[1]}</b><div class="s42-bar"><i style="width:${clamp(r[2]*100,0,100)}%"></i></div></div>`).join('')}
let meta=load();renderMeta(meta);
function nestedGame(){const a=document.getElementById('baseBuild')?.contentDocument;const b=a?.getElementById('stableBuild')?.contentDocument;const c=b?.getElementById('gameFrame')?.contentWindow;return {outer:a,galia:b,game:c}}
function patch(){const {galia,game}=nestedGame();if(!game?.SAG||game.SAG.__month042)return false;const S=game.SAG;S.__month042=true;
  for(const p of extraProfiles)if(!S.profiles.some(x=>x.name===p.name))S.profiles.push(p);
  const baseWeighted=S.weightedProfile;S.weightedProfile=()=>{const phase=phaseFor(meta),unlocked=S.profiles.filter(p=>!p.unlock||p.unlock<=Math.max(S.wave,phase*2));let total=unlocked.reduce((a,p)=>a+p.weight,0),r=Math.random()*total;for(const p of unlocked){r-=p.weight;if(r<=0)return p}return baseWeighted()};
  const baseReset=S.resetGame;S.resetGame=()=>{baseReset();const research=Math.min(12,meta.research),mastery=(meta.combat+meta.exploration+meta.salvage)/30;S.player.damage+=Math.floor(research/6);S.player.speed*=1+Math.min(.14,meta.exploration*.012);S.player.maxHp+=Math.floor(meta.salvage*2.5);S.player.hp=S.player.maxHp;S.player.fireRate*=1-Math.min(.12,meta.combat*.01);S.player.dropBoost*=1+Math.min(.3,mastery*.3);S.frontierPhase=phaseFor(meta)};
  const baseSpawn=S.spawnBoss;S.spawnBoss=()=>{baseSpawn();const available=Math.min(10,2+phaseFor(meta)*2+Math.floor(meta.runs/18));const unseen=bossRoster.slice(0,available).filter(x=>!meta.bosses.includes(x.id));const def=(unseen.length?unseen:bossRoster.slice(0,available))[Math.floor(Math.random()*(unseen.length?unseen.length:available))];const b=S.boss;b.type=def.id;b.name=def.name;b.color=def.color;b.core=def.core;b.pattern=def.pattern;b.move=def.move;b.maxHp=Math.round(b.maxHp*def.hp);b.hp=b.maxHp;b.r=Math.round(48+def.hp*10);b.ability=.5;b.teleport=2.5;b.dashClock=1.4;S.ui.bossText.textContent=def.name;S.showToast(`WARNING // ${def.name} DETECTED`)};
  const baseKill=S.killBoss;S.killBoss=()=>{const id=S.boss?.type||'warden',name=S.boss?.name||'FRONTIER WARDEN';if(!meta.bosses.includes(id))meta.bosses.push(id);meta.commandXp+=55;meta.research=Math.min(12,meta.research+(Math.random()<.42?1:0));meta.campaign=Math.min(8,meta.campaign+(meta.bosses.length%2===0?1:0));save(meta);renderMeta(meta);baseKill();S.showToast(`${name} DESTROYED // CODEX ${meta.bosses.length}/7`)};
  const baseKillEnemy=S.killEnemy;S.killEnemy=e=>{if(e.mode==='splitter'&&!e.splitDone){e.splitDone=true;for(let i=0;i<2;i++){const p=S.profiles.find(x=>x.name==='scout');S.spawnEnemy(p,true);const n=S.enemies[S.enemies.length-1];n.x=e.x+(i?18:-18);n.y=e.y}}if(e.mode==='leech'&&S.player)S.player.hp=Math.min(S.player.maxHp,S.player.hp+2);baseKillEnemy(e)};
  const baseUpdate=S.update;S.update=dt=>{const p=S.player;if(!p)return baseUpdate(dt);const frozen=[];for(const e of S.enemies){if(!['skirmisher','leech','minelayer','disruptor','artillery','commander'].includes(e.mode))continue;const a=Math.atan2(p.y-e.y,p.x-e.x),d=Math.hypot(p.x-e.x,p.y-e.y);e.special=(e.special||1)-dt;let vx=0,vy=0;if(e.mode==='skirmisher'){vx=Math.cos(a)*(d>230?1:-.35)+Math.cos(a+Math.PI/2)*.8;vy=Math.sin(a)*(d>230?1:-.35)+Math.sin(a+Math.PI/2)*.8;if(e.special<=0){for(let i=-1;i<=1;i++)S.enemyShoot(e.x,e.y,a+i*.13,340,e.damage,e.color);e.special=1.8}}else if(e.mode==='leech'){vx=Math.cos(a)*1.15;vy=Math.sin(a)*1.15}else if(e.mode==='minelayer'){vx=Math.cos(a)*(d>310?.5:-.2);vy=Math.sin(a)*(d>310?.5:-.2);if(e.special<=0){for(let i=0;i<6;i++)S.enemyShoot(e.x,e.y,i*Math.PI/3,80,e.damage,e.color);e.special=3.2}}else if(e.mode==='disruptor'){vx=Math.cos(a)*(d>280?.5:-.35);vy=Math.sin(a)*(d>280?.5:-.35);if(e.special<=0){S.enemyShoot(e.x,e.y,a,220,e.damage,e.color);S.enemyShoot(e.x,e.y,a+.28,220,e.damage,e.color);S.enemyShoot(e.x,e.y,a-.28,220,e.damage,e.color);e.special=2.4}}else if(e.mode==='artillery'){vx=Math.cos(a)*(d>410?.35:-.15);vy=Math.sin(a)*(d>410?.35:-.15);if(e.special<=0){S.enemyShoot(e.x,e.y,a,165,e.damage+8,e.color);e.special=3.6}}else if(e.mode==='commander'){vx=Math.cos(a)*(d>360?.25:-.2);vy=Math.sin(a)*(d>360?.25:-.2);if(e.special<=0){for(const ally of S.enemies)if(ally!==e&&Math.hypot(ally.x-e.x,ally.y-e.y)<220)ally.hp=Math.min(ally.maxHp,ally.hp+1);e.special=2.8}}e.x+=vx*e.s*dt;e.y+=vy*e.s*dt;frozen.push([e,e.s]);e.s=0}
    let bossRestore=null;if(S.boss){const b=S.boss,a=Math.atan2(p.y-b.y,p.x-b.x),d=Math.hypot(p.x-b.x,p.y-b.y);b.ability=(b.ability||0)-dt;b.teleport=(b.teleport||0)-dt;b.dashClock=(b.dashClock||0)-dt;let speed=b.s;if(b.move==='orbit'){b.x+=Math.cos(a+Math.PI/2)*speed*.9*dt;b.y+=Math.sin(a+Math.PI/2)*speed*.9*dt}else if(b.move==='strafe'){b.x+=Math.cos(a)*(d>330?.5:-.25)*speed*dt;b.y+=Math.sin(a)*(d>330?.5:-.25)*speed*dt}else if(b.move==='anchor'){b.x+=Math.cos(a)*speed*.18*dt;b.y+=Math.sin(a)*speed*.18*dt}else if(b.move==='dash'&&b.dashClock<=0){b.x+=Math.cos(a)*210;b.y+=Math.sin(a)*210;b.dashClock=2.2}else if(b.move==='blink'&&b.teleport<=0){b.x=80+Math.random()*(S.W-160);b.y=80+Math.random()*(S.H-160);b.teleport=3.3}else{b.x+=Math.cos(a)*speed*.5*dt;b.y+=Math.sin(a)*speed*.5*dt}if(b.ability<=0){fireBossPattern(S,b,a);b.ability=b.pattern==='tempest'?.7:b.pattern==='foundry'?2.7:1.45}bossRestore=[b,b.s,b.shoot,b.summon];b.s=0;b.shoot=999;b.summon=999}
    baseUpdate(dt);for(const [e,s] of frozen)e.s=s;if(bossRestore){const [b,s,shoot,summon]=bossRestore;if(S.boss===b){b.s=s;b.shoot=Math.min(b.shoot,shoot);b.summon=Math.min(b.summon,summon)}}};
  const baseEnd=S.endGame;S.endGame=()=>{const survived=S.elapsed||0;meta.runs++;meta.commandXp+=Math.round(18+S.wave*4+S.bossesKilled*18);meta.contracts=Math.min(18,meta.contracts+(S.wave>=4?1:0)+(S.kills>=80?1:0));meta.combat=Math.min(10,meta.combat+(S.kills>=55?1:0));meta.exploration=Math.min(10,meta.exploration+(S.wave>=5?1:0));meta.salvage=Math.min(10,meta.salvage+(S.score>=3500?1:0));meta.galia=Math.min(10,meta.galia+(S.sector>=3?1:0));meta.bestWave=Math.max(meta.bestWave,S.wave);if(survived>=480)meta.research=Math.min(12,meta.research+1);renderMeta(meta);baseEnd()};
  if(galia){const ribbon=galia.querySelector('.build-ribbon b');if(ribbon)ribbon.textContent='0.42.2';galia.body.dataset.build='0422'}
  return true}
function fireBossPattern(S,b,a){const shot=(ang,spd=280,dmg=12)=>S.enemyShoot(b.x,b.y,ang,spd,dmg,b.color||'#ff668b');switch(b.pattern){case'burst':for(let i=-2;i<=2;i++)shot(a+i*.08,390,13);break;case'rings':for(let i=0;i<16;i++)shot(i*Math.PI/8,230,11);break;case'cross':for(let i=0;i<4;i++){shot(i*Math.PI/2,330,14);shot(i*Math.PI/2+.18,260,10)}break;case'summon':for(let i=0;i<4;i++)S.spawnEnemy(null,true);break;case'prism':for(let i=-3;i<=3;i++)shot(a+i*.16,300+Math.abs(i)*28,12);break;case'gravity':for(let i=0;i<12;i++)shot(i*Math.PI/6+(b.phase||0),145,16);if(S.player){S.player.x+=(b.x-S.player.x)*.018;S.player.y+=(b.y-S.player.y)*.018}break;case'tempest':for(let i=-1;i<=1;i++)shot(a+i*.22,470,14);break;case'foundry':for(let i=0;i<2;i++)S.spawnEnemy(S.profiles[S.profiles.length-1-i],true);for(let i=-2;i<=2;i++)shot(a+i*.25,240,15);break;case'oracle':for(let i=0;i<10;i++)shot(i*Math.PI/5+(b.phase||0)*.4,210,13);b.hp=Math.min(b.maxHp,b.hp+Math.max(1,Math.floor(b.maxHp*.004)));break;default:for(let i=-4;i<=4;i++)shot(a+i*.19,290,12)}}
let tries=0;const timer=setInterval(()=>{tries++;if(patch()||tries>80)clearInterval(timer)},250);
})();